#!/bin/bash
set -e
set -x

export CGO_ENABLED=1

# VERSION=$(go run pkg/version/version.go)
VERSION=$(git describe --tags)

export GOMAXPROCS=4
# also can use: go build -p 4

# LIB_DIR=/usr/lib/x86_64-linux-gnu
LIB_DIR=$(dirname $(dirname $(gcc -print-libgcc-file-name)))

export CGO_CXXFLAGS="-I/usr/include/qt6"
export CGO_LDFLAGS="-L$LIB_DIR -Wl,-rpath,$LIB_DIR"
export PKG_CONFIG_PATH=$LIB_DIR/pkgconfig

#    -ldflags "-static-libgcc -static-libstdc++ -s -w" \

time go build -o ayandict-$VERSION \
	-ldflags '-extldflags "-static"' \
	-trimpath \
	"$@"
