#!/usr/bin/env bash
set -e
set -x

export CGO_ENABLED=1

export CGO_CFLAGS="-Os -ffunction-sections -fdata-sections"
export CGO_CXXFLAGS="-Os -ffunction-sections -fdata-sections"
export CGO_LDFLAGS="-Wl,--gc-sections"

FLAGS=(-ldflags '-s -w -linkmode=external' -trimpath)

# VERSION=$(go run pkg/version/version.go)
VERSION=$(git describe --tags)

export GOMAXPROCS=6
# also can use: go build -p 6

OUT=ayandict-$VERSION-$(go env GOOS)-$(go env GOARCH)

date

time go build -o "$OUT" "${FLAGS[@]}" "$@"

date