#!/usr/bin/env bash
set -e
set -x

FLAGS=(-ldflags '-s -w' -trimpath)
VERSION=$(go run pkg/version/version.go)

export CGO_ENABLED=1
export CGO_CXXFLAGS=-std=c++17
OUT="ayandict-$VERSION-mac-$(go env GOARCH)"
go build -o "$OUT" "${FLAGS[@]}" "$@"
bzip2 -k -f "$OUT"
