#!/bin/bash
set -e
set -x

FLAGS=(-ldflags '-s -w' -trimpath)
VERSION=$(go run pkg/version/version.go)

TARGET=aarch64-macos
export CC="zig cc -target $TARGET -F/host/Frameworks"
export CXX="zig c++ -target $TARGET -F/host/Frameworks"

export CGO_ENABLED=1
export GOOS=darwin
export GOARCH=arm64
OUT=ayandict-$VERSION-mac-arm64
time go build -o $OUT "${FLAGS[@]}" "$@"

