services:
  ayandict-web:
    build:
      context: .
    environment:
      CONFIG_FILE: /app/config.toml
    volumes:
      - "${PWD}/docker-config.toml:/app/config.toml:ro"
      - "${HOME}/.stardict/dic:/root/.stardict/dic:ro"
    ports:
      - "8357:8357"
