name: Windows Build with no GUI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.24

      - name: Build (no GUI)
        shell: pwsh
        run: |
          go env
          go build -v ./cmd/ayandict-nogui/

      - name: CLICK HERE TO DOWNLOAD BINARY
        uses: actions/upload-artifact@v7
        with:
          name: ayandict-nogui-windows-x64-${{ github.sha }}
          path: ayandict-nogui.exe
          retention-days: 7
