# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Linux Build

on:
  push:
    branches: ["v3", "release-linux"]
  pull_request:
    branches: ["v3"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# to disable auto-cancel for a branch main:
# concurrency:
#   group: ${{ github.ref != 'refs/heads/main' && format('{0}-{1}', github.workflow, github.ref) || '' }}
#   cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Go build cache
        if: ${{ github.ref != 'refs/heads/release-linux' }}
        id: download-go-build-cache-linux
        uses: dawidd6/action-download-artifact@v11
        continue-on-error: true
        with:
          # workflow_search=true: the most recent workflow matching all other criteria
          # will be looked up instead of using the current workflow
          workflow_search: true
          workflow_conclusion: success
          event: push
          name: go-build-cache-linux
          path: /home/runner/.cache/go-build
          if_no_artifact_found: ignore
          use_unzip: true
          github_token: ${{ github.token }}

          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          check_artifacts: true
          # Optional, search for the last workflow run whose stored an artifact named as in `name` input
          # default false
          search_artifacts: true

      # - name: Check Go build cache
      #   run: ls -l /home/runner/.cache/go-build || true

      - uses: actions/checkout@v3

      - name: Install Qt6
        run: |
          sudo apt-get update
          sudo apt-get install qt6-base-dev qt6-multimedia-dev

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Build
        run: CGO_ENABLED=1 go build -ldflags '-s -w' -trimpath

      - name: CLICK HERE TO DOWNLOAD BINARY
        uses: actions/upload-artifact@v4
        with:
          name: ayandict-linux-amd64-${{ github.sha }}
          if-no-files-found: error
          retention-days: 7
          path: ayandict

      - name: Upload Go build cache
        uses: actions/upload-artifact@v4
        with:
          name: go-build-cache-linux
          if-no-files-found: error
          retention-days: 7
          path: /home/runner/.cache/go-build
