name: Windows Build with miqt-docker

on:
  push:
    branches: ["build-windows*"]
  pull_request:
    branches: ["v3"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Install miqt-docker
        run: |
          cd /home/runner/go
          mkdir -p src/github.com/ilius
          cd src/github.com/ilius
          git clone https://github.com/ilius/miqt
          cd miqt/cmd/miqt-docker/
          go install

      - name: Build
        run: miqt-docker win64-qt6-static go build

      - name: CLICK HERE TO DOWNLOAD BINARY
        uses: actions/upload-artifact@v4
        with:
          name: ayandict-win64-${{ github.sha }}
          path: ayandict.exe
          retention-days: 7