# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Mac Build

on:
  push:
    branches: ["release-macos"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Show kernel info
        run: uname -a

      - name: Install Qt6
        run: |
          brew update >/dev/null
          brew install gcc cmake ninja openssl@3 zlib qt6 pkg-config

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24

      - name: Build
        run: CGO_ENABLED=1 CGO_CXXFLAGS=-std=c++17 go build
        # -ldflags '-s -w' -trimpath

      - name: CLICK HERE TO DOWNLOAD BINARY
        uses: actions/upload-artifact@v4
        with:
          name: ayandict-mac-arm64-${{ github.sha }}
          if-no-files-found: error
          retention-days: 7
          path: ayandict

      - name: Upload Go build cache
        uses: actions/upload-artifact@v4
        with:
          name: go-build-cache
          if-no-files-found: error
          retention-days: 7
          path: ~/Library/Caches/go-build
