name: Go Test

on:
    push:
        branches: ["main", "v3"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"

            - name: Test
              run: go test -v ./...

            - name: Go vet
              run: go vet
