name: Go Test

on:
  push:
    branches: ["main", "v3"]
  pull_request:
    branches: ["main", "v3"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Test
        run: CGO_ENABLED=1 go test -v ./pkg/dictmgr/internal/dicts/ ./pkg/wordwrap

      # - name: Go vet
      #   run: CGO_ENABLED=1 go vet
